/*
 * This file is generated by jOOQ.
 */
package com.metalheart.model.jooq.tables.records;


import com.metalheart.model.jooq.tables.RunningListArchive;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RunningListArchiveRecord extends UpdatableRecordImpl<RunningListArchiveRecord> implements Record3<Integer, Integer, String> {

    private static final long serialVersionUID = 1951296842;

    /**
     * Setter for <code>public.running_list_archive.year</code>.
     */
    public void setYear(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.running_list_archive.year</code>.
     */
    public Integer getYear() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.running_list_archive.week</code>.
     */
    public void setWeek(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.running_list_archive.week</code>.
     */
    public Integer getWeek() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.running_list_archive.archive</code>.
     */
    public void setArchive(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.running_list_archive.archive</code>.
     */
    public String getArchive() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return RunningListArchive.RUNNING_LIST_ARCHIVE.YEAR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return RunningListArchive.RUNNING_LIST_ARCHIVE.WEEK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return RunningListArchive.RUNNING_LIST_ARCHIVE.ARCHIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getYear();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getWeek();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getArchive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getYear();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getWeek();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getArchive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RunningListArchiveRecord value1(Integer value) {
        setYear(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RunningListArchiveRecord value2(Integer value) {
        setWeek(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RunningListArchiveRecord value3(String value) {
        setArchive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RunningListArchiveRecord values(Integer value1, Integer value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RunningListArchiveRecord
     */
    public RunningListArchiveRecord() {
        super(RunningListArchive.RUNNING_LIST_ARCHIVE);
    }

    /**
     * Create a detached, initialised RunningListArchiveRecord
     */
    public RunningListArchiveRecord(Integer year, Integer week, String archive) {
        super(RunningListArchive.RUNNING_LIST_ARCHIVE);

        set(0, year);
        set(1, week);
        set(2, archive);
    }
}
