/*
 * This file is generated by jOOQ.
 */
package com.metalheart.model.jooq.tables.records;


import com.metalheart.model.jooq.enums.TaskStatusEnum;
import com.metalheart.model.jooq.tables.WeekWorkLog;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WeekWorkLogRecord extends UpdatableRecordImpl<WeekWorkLogRecord> implements Record3<Integer, Integer, TaskStatusEnum> {

    private static final long serialVersionUID = -1631670416;

    /**
     * Setter for <code>public.week_work_log.task_id</code>.
     */
    public void setTaskId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.week_work_log.task_id</code>.
     */
    public Integer getTaskId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.week_work_log.day_index</code>.
     */
    public void setDayIndex(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.week_work_log.day_index</code>.
     */
    public Integer getDayIndex() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.week_work_log.status</code>.
     */
    public void setStatus(TaskStatusEnum value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.week_work_log.status</code>.
     */
    public TaskStatusEnum getStatus() {
        return (TaskStatusEnum) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, TaskStatusEnum> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, TaskStatusEnum> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return WeekWorkLog.WEEK_WORK_LOG.TASK_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return WeekWorkLog.WEEK_WORK_LOG.DAY_INDEX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<TaskStatusEnum> field3() {
        return WeekWorkLog.WEEK_WORK_LOG.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getTaskId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getDayIndex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TaskStatusEnum component3() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getTaskId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getDayIndex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TaskStatusEnum value3() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WeekWorkLogRecord value1(Integer value) {
        setTaskId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WeekWorkLogRecord value2(Integer value) {
        setDayIndex(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WeekWorkLogRecord value3(TaskStatusEnum value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WeekWorkLogRecord values(Integer value1, Integer value2, TaskStatusEnum value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WeekWorkLogRecord
     */
    public WeekWorkLogRecord() {
        super(WeekWorkLog.WEEK_WORK_LOG);
    }

    /**
     * Create a detached, initialised WeekWorkLogRecord
     */
    public WeekWorkLogRecord(Integer taskId, Integer dayIndex, TaskStatusEnum status) {
        super(WeekWorkLog.WEEK_WORK_LOG);

        set(0, taskId);
        set(1, dayIndex);
        set(2, status);
    }
}
