server:
  port: 8443
  ssl:
    key-store-type: PKCS12
    key-store: ${SECURE_KEYSTORE_PATH}
    key-store-password: ${SECURE_KEYSTORE_PASS}
spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  security.oauth2.client.registration:
    google:
      client-id: ${OAUTH2_GOOGLE_CLIENT_ID}
      client-secret: ${OAUTH2_GOOGLE_CLIENT_SECRET}
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 25
    username: ${SMTP_GOOGLE_USERNAME}
    password: ${SMTP_GOOGLE_PASSWORD}
    properties.mail.smtp:
      auth: true
      starttls.enable: true
taskmanager:
  security:
    defaultUsername: ${DEFAULT_ADMIN_USERNAME}
    defaultEmail: admin@email.com
    defaultPassword: ${DEFAULT_ADMIN_PASSWORD}
  rest:
    maxPayloadLength: 10000
    includeRequest: true
    includeRequestHeaders: false
    includeResponse: false
    includeResponseHeaders: false
    backUrl: ${BACK_URL}
    frontUrl: ${FRONT_URL}
