/*
 * This file is generated by jOOQ.
 */
package com.metalheart.model.jooq.tables;


import com.metalheart.model.jooq.Indexes;
import com.metalheart.model.jooq.Keys;
import com.metalheart.model.jooq.Public;
import com.metalheart.model.jooq.enums.TaskStatusEnum;
import com.metalheart.model.jooq.tables.records.WeekWorkLogRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WeekWorkLog extends TableImpl<WeekWorkLogRecord> {

    private static final long serialVersionUID = 491674362;

    /**
     * The reference instance of <code>public.week_work_log</code>
     */
    public static final WeekWorkLog WEEK_WORK_LOG = new WeekWorkLog();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WeekWorkLogRecord> getRecordType() {
        return WeekWorkLogRecord.class;
    }

    /**
     * The column <code>public.week_work_log.task_id</code>.
     */
    public final TableField<WeekWorkLogRecord, Integer> TASK_ID = createField("task_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.week_work_log.day_index</code>.
     */
    public final TableField<WeekWorkLogRecord, Integer> DAY_INDEX = createField("day_index", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.week_work_log.status</code>.
     */
    public final TableField<WeekWorkLogRecord, TaskStatusEnum> STATUS = createField("status", org.jooq.impl.SQLDataType.VARCHAR.nullable(false).asEnumDataType(com.metalheart.model.jooq.enums.TaskStatusEnum.class), this, "");

    /**
     * Create a <code>public.week_work_log</code> table reference
     */
    public WeekWorkLog() {
        this(DSL.name("week_work_log"), null);
    }

    /**
     * Create an aliased <code>public.week_work_log</code> table reference
     */
    public WeekWorkLog(String alias) {
        this(DSL.name(alias), WEEK_WORK_LOG);
    }

    /**
     * Create an aliased <code>public.week_work_log</code> table reference
     */
    public WeekWorkLog(Name alias) {
        this(alias, WEEK_WORK_LOG);
    }

    private WeekWorkLog(Name alias, Table<WeekWorkLogRecord> aliased) {
        this(alias, aliased, null);
    }

    private WeekWorkLog(Name alias, Table<WeekWorkLogRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> WeekWorkLog(Table<O> child, ForeignKey<O, WeekWorkLogRecord> key) {
        super(child, key, WEEK_WORK_LOG);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.WEEK_WORK_LOG_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<WeekWorkLogRecord> getPrimaryKey() {
        return Keys.WEEK_WORK_LOG_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<WeekWorkLogRecord>> getKeys() {
        return Arrays.<UniqueKey<WeekWorkLogRecord>>asList(Keys.WEEK_WORK_LOG_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WeekWorkLog as(String alias) {
        return new WeekWorkLog(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WeekWorkLog as(Name alias) {
        return new WeekWorkLog(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public WeekWorkLog rename(String name) {
        return new WeekWorkLog(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public WeekWorkLog rename(Name name) {
        return new WeekWorkLog(name, null);
    }
}
